/*
 * generated by Xtext
 */
package com.ponta027.swc.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractToolValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.ponta027.swc.tool.ToolPackage.eINSTANCE);
		return result;
	}
}
