/*
 * generated by Xtext
 */
package com.ponta027.swc;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ToolUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return com.ponta027.swc.ui.internal.ToolActivator.getInstance().getInjector("com.ponta027.swc.Tool");
	}
	
}
