/*
 * generated by Xtext
 */
package com.ponta027.swc.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.ponta027.swc.ui.internal.ToolActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ToolExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ToolActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ToolActivator.getInstance().getInjector(ToolActivator.COM_PONTA027_SWC_TOOL);
	}
	
}
