/*
 * generated by Xtext
 */
package com.ponta027.swc.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ToolUiModule extends com.ponta027.swc.ui.AbstractToolUiModule {
	public ToolUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
