/*
 * generated by Xtext
 */
package com.ponta027.swc;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ToolRuntimeModule extends com.ponta027.swc.AbstractToolRuntimeModule {

}
