/*
 * generated by Xtext
 */
package com.ponta027.swc;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ToolStandaloneSetup extends ToolStandaloneSetupGenerated{

	public static void doSetup() {
		new ToolStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

