/*
 * generated by Xtext
 */
package com.ponta027.swc.ui.contentassist

import com.ponta027.swc.ui.contentassist.AbstractToolProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class ToolProposalProvider extends AbstractToolProposalProvider {
}
